### PR TITLE
Fix route preview zero votes

### PR DESCRIPTION
**Pull request by NejcS**
There are two changes in this PR:
1. If route only has a base grade, don't render the distribution chart in the route preview.
2. If route doesn't have comments, don't render the route comments component in route preview. Same for difficulty votes.

This caused that I had to slightly change how the `childViewsInitialized` object is used.

### CODE REVIEW

**Comment by salamca** [comment]
Route with no preview content still expands a bit>
image

But only if it is clicked after another nonempty info panel is expanded.

Could we also remove leftover 'popover' code (html and scss)?

**Comment by demshy** [comment]
Found another minor issue: 
Clicking the "add to log" checkbox in route list shouldn't expand the accordion.

**Comment by NejcS** [comment]
Both issues should be solved now.

**Comment by NejcS** [comment]
Also fixes https://github.com/plezanje-net/web/issues/184

**Review by salamca — APPROVED** [review]

**Pull request merged**
